apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: najlaebk1/user_images
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service:8762/eureka
            - name: CONFIG_SERVICE_URL
              value: http://config-service:9999
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
---
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer